import type { Metadata, Viewport } from 'next'
import './globals.css'

export const metadata: Metadata = {
    title: 'Harshit Sharma - Full Stack Developer in Jodhpur | Next.js Developer Rajasthan',
    description: 'Harshit Sharma - Expert Full Stack Developer in Jodhpur, Rajasthan. Specializing in Next.js, React.js, Node.js, AI/ML solutions. 4.5+ years experience. Best web developer in Jodhpur for modern web applications.',
    keywords: [
        'Harshit Sharma',
        'Full Stack Developer Jodhpur',
        'Next.js Developer Rajasthan',
        'React Developer Jodhpur',
        'Web Developer Jodhpur',
        'MERN Stack Developer Rajasthan',
        'JavaScript Developer Jodhpur',
        'Node.js Developer Rajasthan',
        'AI Developer Jodhpur',
        'Frontend Developer Jodhpur',
        'Backend Developer Rajasthan',
        'Software Developer Jodhpur',
        'Web Development Services Jodhpur',
        'React.js Developer Rajasthan',
        'TypeScript Developer Jodhpur',
        'MongoDB Developer Rajasthan',
        'Express.js Developer Jodhpur',
        'API Development Jodhpur',
        'E-commerce Developer Rajasthan',
        'Mobile App Developer Jodhpur',
        'UI/UX Developer Rajasthan',
        'Freelance Developer Jodhpur',
        'Website Developer Jodhpur',
        'Custom Software Development Rajasthan',
        'Database Developer Jodhpur',
        'Cloud Developer Rajasthan',
        'AWS Developer Jodhpur',
        'DevOps Developer Rajasthan',
        'Startup Developer Jodhpur',
        'Enterprise Developer Rajasthan',
        'SaaS Developer Jodhpur',
        'LangChain Developer Rajasthan',
        'OpenAI Developer Jodhpur',
        'Machine Learning Developer Rajasthan',
        'Automation Developer Jodhpur',
        'Team Lead Developer Rajasthan',
        'Senior Developer Jodhpur',
        'Tech Lead Rajasthan',
        'Software Engineer Jodhpur',
        'Web Application Developer Rajasthan',
        'Progressive Web App Developer Jodhpur',
        'Responsive Web Developer Rajasthan',
        'SEO Optimized Developer Jodhpur',
        'Performance Optimization Developer Rajasthan',
        'Security Expert Developer Jodhpur',
        'Scalable Solutions Developer Rajasthan',
        'Microservices Developer Jodhpur',
        'REST API Developer Rajasthan',
        'GraphQL Developer Jodhpur',
        'Real-time Applications Developer Rajasthan',
        'Chat Applications Developer Jodhpur',
        'Payment Integration Developer Rajasthan',
        'Third-party API Integration Jodhpur',
        'CMS Developer Rajasthan',
        'Headless CMS Developer Jodhpur',
        'JAMstack Developer Rajasthan',
        'Serverless Developer Jodhpur',
        'Docker Developer Rajasthan',
        'Kubernetes Developer Jodhpur',
        'CI/CD Developer Rajasthan',
        'Git Expert Jodhpur',
        'Code Review Expert Rajasthan',
        'Agile Developer Jodhpur',
        'Scrum Master Rajasthan',
        'Technical Consultant Jodhpur',
        'IT Solutions Rajasthan',
        'Digital Transformation Jodhpur',
        'Business Automation Rajasthan',
        'Workflow Automation Jodhpur',
        'Data Analytics Developer Rajasthan',
        'Dashboard Developer Jodhpur',
        'Reporting Solutions Rajasthan',
        'Integration Specialist Jodhpur',
        'Migration Expert Rajasthan',
        'Legacy System Modernization Jodhpur',
        'Code Optimization Rajasthan',
        'Bug Fixing Expert Jodhpur',
        'Maintenance Services Rajasthan',
        'Support Services Jodhpur',
        'Training Services Rajasthan',
        'Mentoring Services Jodhpur',
        'Code Quality Expert Rajasthan',
        'Best Practices Consultant Jodhpur',
        'Architecture Design Rajasthan',
        'System Design Jodhpur',
        'Database Design Rajasthan',
        'Performance Tuning Jodhpur',
        'Load Testing Rajasthan',
        'Security Audit Jodhpur',
        'Penetration Testing Rajasthan',
        'Compliance Solutions Jodhpur',
        'GDPR Compliance Rajasthan',
        'Accessibility Expert Jodhpur',
        'WCAG Compliance Rajasthan',
        'Cross-browser Compatibility Jodhpur',
        'Mobile Responsive Rajasthan',
        'PWA Developer Jodhpur',
        'Offline-first Applications Rajasthan',
        'Real-time Sync Jodhpur',
        'Multi-tenant Applications Rajasthan',
        'White-label Solutions Jodhpur',
        'Custom Integrations Rajasthan',
        'Webhook Development Jodhpur',
        'Event-driven Architecture Rajasthan',
        'Message Queue Systems Jodhpur',
        'Caching Solutions Rajasthan',
        'CDN Implementation Jodhpur',
        'Image Optimization Rajasthan',
        'Video Streaming Solutions Jodhpur',
        'File Upload Systems Rajasthan',
        'Search Implementation Jodhpur',
        'Elasticsearch Developer Rajasthan',
        'Analytics Implementation Jodhpur',
        'A/B Testing Solutions Rajasthan',
        'Conversion Optimization Jodhpur',
        'User Experience Optimization Rajasthan',
        'Page Speed Optimization Jodhpur',
        'Core Web Vitals Expert Rajasthan',
        'Technical SEO Jodhpur',
        'Schema Markup Rajasthan',
        'Structured Data Jodhpur',
        'Meta Tags Optimization Rajasthan',
        'Social Media Integration Jodhpur',
        'Email Integration Rajasthan',
        'SMS Integration Jodhpur',
        'Push Notifications Rajasthan',
        'WebRTC Developer Jodhpur',
        'Socket.io Expert Rajasthan',
        'WebSocket Implementation Jodhpur',
        'Server-sent Events Rajasthan',
        'Background Jobs Jodhpur',
        'Cron Jobs Rajasthan',
        'Task Scheduling Jodhpur',
        'Queue Management Rajasthan',
        'Error Handling Expert Jodhpur',
        'Logging Solutions Rajasthan',
        'Monitoring Implementation Jodhpur',
        'Health Checks Rajasthan',
        'Uptime Monitoring Jodhpur',
        'Performance Monitoring Rajasthan',
        'User Analytics Jodhpur',
        'Business Intelligence Rajasthan',
        'Data Visualization Jodhpur',
        'Chart Implementation Rajasthan',
        'Report Generation Jodhpur',
        'PDF Generation Rajasthan',
        'Excel Export Jodhpur',
        'Data Import/Export Rajasthan',
        'Bulk Operations Jodhpur',
        'Batch Processing Rajasthan',
        'Stream Processing Jodhpur',
        'Event Sourcing Rajasthan',
        'CQRS Implementation Jodhpur',
        'Domain-driven Design Rajasthan',
        'Clean Architecture Jodhpur',
        'Hexagonal Architecture Rajasthan',
        'Onion Architecture Jodhpur',
        'Layered Architecture Rajasthan',
        'Component-based Architecture Jodhpur',
        'Modular Architecture Rajasthan',
        'Plugin Architecture Jodhpur',
        'Extension Development Rajasthan',
        'Theme Development Jodhpur',
        'Template Development Rajasthan',
        'Component Library Jodhpur',
        'Design System Rajasthan',
        'Style Guide Implementation Jodhpur',
        'Brand Guidelines Rajasthan',
        'UI Kit Development Jodhpur',
        'Storybook Implementation Rajasthan',
        'Documentation Expert Jodhpur',
        'API Documentation Rajasthan',
        'Technical Writing Jodhpur',
        'Code Documentation Rajasthan',
        'User Manual Creation Jodhpur',
        'Training Material Rajasthan',
        'Video Tutorials Jodhpur',
        'Workshop Conductor Rajasthan',
        'Bootcamp Instructor Jodhpur',
        'Corporate Training Rajasthan',
        'Team Building Jodhpur',
        'Leadership Skills Rajasthan',
        'Project Management Jodhpur',
        'Resource Planning Rajasthan',
        'Timeline Management Jodhpur',
        'Budget Management Rajasthan',
        'Risk Assessment Jodhpur',
        'Quality Assurance Rajasthan',
        'Testing Strategy Jodhpur',
        'Test Automation Rajasthan',
        'Unit Testing Jodhpur',
        'Integration Testing Rajasthan',
        'End-to-end Testing Jodhpur',
        'Performance Testing Rajasthan',
        'Security Testing Jodhpur',
        'Usability Testing Rajasthan',
        'Accessibility Testing Jodhpur',
        'Cross-platform Testing Rajasthan',
        'Device Testing Jodhpur',
        'Browser Testing Rajasthan',
        'Regression Testing Jodhpur',
        'Smoke Testing Rajasthan',
        'Sanity Testing Jodhpur',
        'User Acceptance Testing Rajasthan',
        'Beta Testing Jodhpur',
        'Load Testing Rajasthan',
        'Stress Testing Jodhpur',
        'Volume Testing Rajasthan',
        'Spike Testing Jodhpur',
        'Endurance Testing Rajasthan',
        'Scalability Testing Jodhpur',
        'Compatibility Testing Rajasthan',
        'Localization Testing Jodhpur',
        'Internationalization Rajasthan',
        'Multi-language Support Jodhpur',
        'Currency Support Rajasthan',
        'Timezone Support Jodhpur',
        'Regional Compliance Rajasthan',
        'Local Business Solutions Jodhpur',
        'Regional SEO Rajasthan',
        'Local Market Expert Jodhpur',
        'Rajasthan Tech Community',
        'Jodhpur Developer Community',
        'Tech Meetups Rajasthan',
        'Developer Events Jodhpur',
        'Hackathon Participant Rajasthan',
        'Open Source Contributor Jodhpur',
        'GitHub Expert Rajasthan',
        'Stack Overflow Contributor Jodhpur',
        'Tech Blogger Rajasthan',
        'Conference Speaker Jodhpur',
        'Workshop Speaker Rajasthan',
        'Podcast Guest Jodhpur',
        'Interview Expert Rajasthan',
        'Technical Interviewer Jodhpur',
        'Hiring Consultant Rajasthan',
        'Team Scaling Expert Jodhpur',
        'Remote Work Expert Rajasthan',
        'Distributed Teams Jodhpur',
        'Collaboration Tools Rajasthan',
        'Communication Expert Jodhpur',
        'Client Relations Rajasthan',
        'Stakeholder Management Jodhpur',
        'Requirement Analysis Rajasthan',
        'Business Analysis Jodhpur',
        'Solution Architecture Rajasthan',
        'Technical Specification Jodhpur',
        'Proof of Concept Rajasthan',
        'MVP Development Jodhpur',
        'Rapid Prototyping Rajasthan',
        'Agile Development Jodhpur',
        'Scrum Implementation Rajasthan',
        'Kanban Expert Jodhpur',
        'Lean Development Rajasthan',
        'DevOps Culture Jodhpur',
        'Continuous Integration Rajasthan',
        'Continuous Deployment Jodhpur',
        'Infrastructure as Code Rajasthan',
        'Configuration Management Jodhpur',
        'Environment Management Rajasthan',
        'Release Management Jodhpur',
        'Version Control Rajasthan',
        'Branch Strategy Jodhpur',
        'Code Review Process Rajasthan',
        'Pull Request Management Jodhpur',
        'Merge Conflict Resolution Rajasthan',
        'Hotfix Management Jodhpur',
        'Emergency Response Rajasthan',
        'Incident Management Jodhpur',
        'Problem Resolution Rajasthan',
        'Root Cause Analysis Jodhpur',
        'Preventive Measures Rajasthan',
        'Disaster Recovery Jodhpur',
        'Business Continuity Rajasthan',
        'Backup Solutions Jodhpur',
        'Data Recovery Rajasthan',
        'Security Incident Response Jodhpur',
        'Vulnerability Assessment Rajasthan',
        'Security Hardening Jodhpur',
        'Encryption Implementation Rajasthan',
        'Authentication Systems Jodhpur',
        'Authorization Framework Rajasthan',
        'Single Sign-On Jodhpur',
        'Multi-factor Authentication Rajasthan',
        'OAuth Implementation Jodhpur',
        'JWT Expert Rajasthan',
        'Session Management Jodhpur',
        'Cookie Security Rajasthan',
        'CSRF Protection Jodhpur',
        'XSS Prevention Rajasthan',
        'SQL Injection Prevention Jodhpur',
        'Input Validation Rajasthan',
        'Output Encoding Jodhpur',
        'Secure Coding Rajasthan',
        'Code Security Audit Jodhpur',
        'Dependency Security Rajasthan',
        'Supply Chain Security Jodhpur',
        'Container Security Rajasthan',
        'Cloud Security Jodhpur',
        'Network Security Rajasthan',
        'Firewall Configuration Jodhpur',
        'VPN Setup Rajasthan',
        'SSL/TLS Implementation Jodhpur',
        'Certificate Management Rajasthan',
        'Domain Security Jodhpur',
        'DNS Security Rajasthan',
        'Email Security Jodhpur',
        'DMARC Implementation Rajasthan',
        'SPF Records Jodhpur',
        'DKIM Setup Rajasthan',
        'Anti-spam Solutions Jodhpur',
        'Phishing Protection Rajasthan',
        'Malware Detection Jodhpur',
        'Virus Scanning Rajasthan',
        'Content Filtering Jodhpur',
        'Web Application Firewall Rajasthan',
        'DDoS Protection Jodhpur',
        'Rate Limiting Rajasthan',
        'Traffic Management Jodhpur',
        'Load Balancing Rajasthan',
        'Auto Scaling Jodhpur',
        'Resource Optimization Rajasthan',
        'Cost Optimization Jodhpur',
        'Cloud Migration Rajasthan',
        'Multi-cloud Strategy Jodhpur',
        'Hybrid Cloud Rajasthan',
        'Edge Computing Jodhpur',
        'CDN Optimization Rajasthan',
        'Global Distribution Jodhpur',
        'Latency Optimization Rajasthan',
        'Bandwidth Optimization Jodhpur',
        'Compression Techniques Rajasthan',
        'Minification Expert Jodhpur',
        'Bundle Optimization Rajasthan',
        'Tree Shaking Jodhpur',
        'Code Splitting Rajasthan',
        'Lazy Loading Jodhpur',
        'Progressive Loading Rajasthan',
        'Skeleton Screens Jodhpur',
        'Loading Optimization Rajasthan',
        'User Experience Jodhpur',
        'User Interface Rajasthan',
        'Interaction Design Jodhpur',
        'Animation Expert Rajasthan',
        'Micro-interactions Jodhpur',
        'Gesture Recognition Rajasthan',
        'Touch Optimization Jodhpur',
        'Voice Interface Rajasthan',
        'Chatbot Development Jodhpur',
        'AI Integration Rajasthan',
        'Machine Learning Jodhpur',
        'Natural Language Processing Rajasthan',
        'Computer Vision Jodhpur',
        'Image Recognition Rajasthan',
        'OCR Implementation Jodhpur',
        'Barcode Scanning Rajasthan',
        'QR Code Generation Jodhpur',
        'Geolocation Services Rajasthan',
        'Maps Integration Jodhpur',
        'GPS Tracking Rajasthan',
        'Location-based Services Jodhpur',
        'Proximity Detection Rajasthan',
        'Beacon Technology Jodhpur',
        'IoT Integration Rajasthan',
        'Sensor Data Processing Jodhpur',
        'Device Communication Rajasthan',
        'Protocol Implementation Jodhpur',
        'Hardware Integration Rajasthan',
        'Embedded Systems Jodhpur',
        'Firmware Development Rajasthan',
        'Cross-platform Development Jodhpur',
        'Native App Development Rajasthan',
        'Hybrid App Development Jodhpur',
        'Web App Development Rajasthan',
        'Desktop App Development Jodhpur',
        'Chrome Extension Rajasthan',
        'Browser Plugin Jodhpur',
        'Add-on Development Rajasthan',
        'Widget Development Jodhpur',
        'Gadget Development Rajasthan',
        'Tool Development Jodhpur',
        'Utility Development Rajasthan',
        'Script Development Jodhpur',
        'Automation Scripts Rajasthan',
        'Build Scripts Jodhpur',
        'Deployment Scripts Rajasthan',
        'Migration Scripts Jodhpur',
        'Data Scripts Rajasthan',
        'Cleanup Scripts Jodhpur',
        'Maintenance Scripts Rajasthan',
        'Monitoring Scripts Jodhpur',
        'Alert Scripts Rajasthan',
        'Notification Systems Jodhpur',
        'Communication Systems Rajasthan',
        'Messaging Systems Jodhpur',
        'Chat Systems Rajasthan',
        'Forum Development Jodhpur',
        'Community Platform Rajasthan',
        'Social Network Jodhpur',
        'Dating Platform Rajasthan',
        'Marketplace Development Jodhpur',
        'Auction Platform Rajasthan',
        'Booking System Jodhpur',
        'Reservation System Rajasthan',
        'Appointment Scheduling Jodhpur',
        'Calendar Integration Rajasthan',
        'Event Management Jodhpur',
        'Ticketing System Rajasthan',
        'Payment Gateway Jodhpur',
        'Billing System Rajasthan',
        'Invoice Generation Jodhpur',
        'Subscription Management Rajasthan',
        'Recurring Payments Jodhpur',
        'Refund Processing Rajasthan',
        'Chargeback Handling Jodhpur',
        'Fraud Detection Rajasthan',
        'Risk Management Jodhpur',
        'Compliance Management Rajasthan',
        'Audit Trail Jodhpur',
        'Activity Logging Rajasthan',
        'User Tracking Jodhpur',
        'Behavior Analysis Rajasthan',
        'Conversion Tracking Jodhpur',
        'Goal Tracking Rajasthan',
        'KPI Dashboard Jodhpur',
        'Metrics Collection Rajasthan',
        'Data Pipeline Jodhpur',
        'ETL Processes Rajasthan',
        'Data Warehouse Jodhpur',
        'Data Lake Rajasthan',
        'Big Data Solutions Jodhpur',
        'Real-time Analytics Rajasthan',
        'Streaming Analytics Jodhpur',
        'Predictive Analytics Rajasthan',
        'Recommendation Engine Jodhpur',
        'Personalization Engine Rajasthan',
        'Content Management Jodhpur',
        'Digital Asset Management Rajasthan',
        'Document Management Jodhpur',
        'File Management Rajasthan',
        'Version Control System Jodhpur',
        'Workflow Management Rajasthan',
        'Process Automation Jodhpur',
        'Business Process Management Rajasthan',
        'Enterprise Resource Planning Jodhpur',
        'Customer Relationship Management Rajasthan',
        'Supply Chain Management Jodhpur',
        'Inventory Management Rajasthan',
        'Asset Management Jodhpur',
        'Project Portfolio Management Rajasthan',
        'Human Resource Management Jodhpur',
        'Payroll Management Rajasthan',
        'Time Tracking Jodhpur',
        'Attendance Management Rajasthan',
        'Performance Management Jodhpur',
        'Learning Management Rajasthan',
        'Knowledge Management Jodhpur',
        'Help Desk System Rajasthan',
        'Ticketing System Jodhpur',
        'Support Portal Rajasthan',
        'FAQ System Jodhpur',
        'Documentation Portal Rajasthan',
        'Wiki Development Jodhpur',
        'Blog Platform Rajasthan',
        'News Portal Jodhpur',
        'Magazine Platform Rajasthan',
        'Publishing Platform Jodhpur',
        'Content Delivery Rajasthan',
        'Media Streaming Jodhpur',
        'Video Platform Rajasthan',
        'Audio Platform Jodhpur',
        'Podcast Platform Rajasthan',
        'Radio Platform Jodhpur',
        'Broadcasting System Rajasthan',
        'Live Streaming Jodhpur',
        'Video Conferencing Rajasthan',
        'Webinar Platform Jodhpur',
        'Online Meeting Rajasthan',
        'Collaboration Platform Jodhpur',
        'Team Communication Rajasthan',
        'Project Collaboration Jodhpur',
        'File Sharing Rajasthan',
        'Screen Sharing Jodhpur',
        'Remote Desktop Rajasthan',
        'Virtual Private Network Jodhpur',
        'Remote Access Rajasthan',
        'Cloud Storage Jodhpur',
        'Backup Service Rajasthan',
        'Sync Service Jodhpur',
        'Migration Service Rajasthan',
        'Integration Service Jodhpur',
        'Consulting Service Rajasthan',
        'Advisory Service Jodhpur',
        'Strategy Consulting Rajasthan',
        'Technology Consulting Jodhpur',
        'Digital Strategy Rajasthan',
        'Innovation Consulting Jodhpur',
        'Transformation Consulting Rajasthan',
        'Change Management Jodhpur',
        'Process Improvement Rajasthan',
        'Efficiency Optimization Jodhpur',
        'Productivity Enhancement Rajasthan',
        'Performance Improvement Jodhpur',
        'Quality Enhancement Rajasthan',
        'Customer Experience Jodhpur',
        'User Satisfaction Rajasthan',
        'Client Success Jodhpur',
        'Relationship Management Rajasthan',
        'Account Management Jodhpur',
        'Partnership Development Rajasthan',
        'Alliance Management Jodhpur',
        'Vendor Management Rajasthan',
        'Supplier Relations Jodhpur',
        'Contract Management Rajasthan',
        'Procurement Solutions Jodhpur',
        'Sourcing Solutions Rajasthan',
        'Cost Management Jodhpur',
        'Budget Planning Rajasthan',
        'Financial Planning Jodhpur',
        'Revenue Optimization Rajasthan',
        'Profit Maximization Jodhpur',
        'Growth Strategy Rajasthan',
        'Market Expansion Jodhpur',
        'Business Development Rajasthan',
        'Sales Automation Jodhpur',
        'Marketing Automation Rajasthan',
        'Lead Generation Jodhpur',
        'Customer Acquisition Rajasthan',
        'Retention Strategy Jodhpur',
        'Loyalty Program Rajasthan',
        'Referral Program Jodhpur',
        'Affiliate Program Rajasthan',
        'Partner Program Jodhpur',
        'Reseller Program Rajasthan',
        'Channel Management Jodhpur',
        'Distribution Management Rajasthan',
        'Logistics Management Jodhpur',
        'Transportation Management Rajasthan',
        'Fleet Management Jodhpur',
        'Route Optimization Rajasthan',
        'Delivery Management Jodhpur',
        'Shipping Integration Rajasthan',
        'Tracking System Jodhpur',
        'Order Management Rajasthan',
        'Fulfillment Center Jodhpur',
        'Warehouse Management Rajasthan',
        'Stock Management Jodhpur',
        'Demand Planning Rajasthan',
        'Supply Planning Jodhpur',
        'Capacity Planning Rajasthan',
        'Resource Allocation Jodhpur',
        'Scheduling Optimization Rajasthan',
        'Workflow Optimization Jodhpur',
        'Process Optimization Rajasthan',
        'System Optimization Jodhpur',
        'Database Optimization Rajasthan',
        'Query Optimization Jodhpur',
        'Index Optimization Rajasthan',
        'Storage Optimization Jodhpur',
        'Memory Optimization Rajasthan',
        'CPU Optimization Jodhpur',
        'Network Optimization Rajasthan',
        'Bandwidth Optimization Jodhpur',
        'Latency Reduction Rajasthan',
        'Response Time Optimization Jodhpur',
        'Throughput Optimization Rajasthan',
        'Scalability Enhancement Jodhpur',
        'Reliability Improvement Rajasthan',
        'Availability Enhancement Jodhpur',
        'Fault Tolerance Rajasthan',
        'Error Recovery Jodhpur',
        'Graceful Degradation Rajasthan',
        'Circuit Breaker Pattern Jodhpur',
        'Retry Mechanism Rajasthan',
        'Timeout Handling Jodhpur',
        'Rate Limiting Rajasthan',
        'Throttling Mechanism Jodhpur',
        'Queue Management Rajasthan',
        'Buffer Management Jodhpur',
        'Cache Management Rajasthan',
        'Session Management Jodhpur',
        'State Management Rajasthan',
        'Configuration Management Jodhpur',
        'Environment Management Rajasthan',
        'Deployment Management Jodhpur',
        'Release Management Rajasthan',
        'Change Management Jodhpur',
        'Version Management Rajasthan',
        'Patch Management Jodhpur',
        'Update Management Rajasthan',
        'Maintenance Management Jodhpur',
        'Support Management Rajasthan',
        'Service Management Jodhpur',
        'Operations Management Rajasthan',
        'Infrastructure Management Jodhpur',
        'Platform Management Rajasthan',
        'Application Management Jodhpur',
        'Data Management Rajasthan',
        'Security Management Jodhpur',
        'Compliance Management Rajasthan',
        'Risk Management Jodhpur',
        'Governance Framework Rajasthan',
        'Policy Management Jodhpur',
        'Procedure Management Rajasthan',
        'Standard Operating Procedures Jodhpur',
        'Best Practices Implementation Rajasthan',
        'Framework Implementation Jodhpur',
        'Methodology Implementation Rajasthan',
        'Tool Implementation Jodhpur',
        'Technology Implementation Rajasthan',
        'Solution Implementation Jodhpur',
        'System Implementation Rajasthan',
        'Process Implementation Jodhpur',
        'Service Implementation Rajasthan',
        'Feature Implementation Jodhpur',
        'Enhancement Implementation Rajasthan',
        'Improvement Implementation Jodhpur',
        'Optimization Implementation Rajasthan',
        'Integration Implementation Jodhpur',
        'Migration Implementation Rajasthan',
        'Upgrade Implementation Jodhpur',
        'Modernization Implementation Rajasthan',
        'Transformation Implementation Jodhpur',
        'Innovation Implementation Rajasthan',
        'Digital Implementation Jodhpur',
        'Technology Adoption Rajasthan',
        'Digital Adoption Jodhpur',
        'Change Adoption Rajasthan',
        'User Adoption Jodhpur',
        'Team Adoption Rajasthan',
        'Organization Adoption Jodhpur',
        'Enterprise Adoption Rajasthan',
        'Industry Adoption Jodhpur',
        'Market Adoption Rajasthan',
        'Regional Adoption Jodhpur',
        'Local Adoption Rajasthan',
        'Community Adoption Jodhpur',
        'Ecosystem Adoption Rajasthan',
        'Platform Adoption Jodhpur',
        'Standard Adoption Rajasthan',
        'Protocol Adoption Jodhpur',
        'Framework Adoption Rajasthan',
        'Methodology Adoption Jodhpur',
        'Practice Adoption Rajasthan',
        'Culture Adoption Jodhpur',
        'Mindset Adoption Rajasthan',
        'Behavior Adoption Jodhpur',
        'Skill Adoption Rajasthan',
        'Knowledge Adoption Jodhpur',
        'Learning Adoption Rajasthan',
        'Training Adoption Jodhpur',
        'Development Adoption Rajasthan',
        'Growth Adoption Jodhpur',
        'Success Adoption Rajasthan',
        'Excellence Adoption Jodhpur',
        'Quality Adoption Rajasthan',
        'Performance Adoption Jodhpur',
        'Efficiency Adoption Rajasthan',
        'Productivity Adoption Jodhpur',
        'Innovation Adoption Rajasthan',
        'Creativity Adoption Jodhpur',
        'Problem Solving Rajasthan',
        'Solution Finding Jodhpur',
        'Decision Making Rajasthan',
        'Strategic Thinking Jodhpur',
        'Critical Thinking Rajasthan',
        'Analytical Thinking Jodhpur',
        'Systems Thinking Rajasthan',
        'Design Thinking Jodhpur',
        'Lean Thinking Rajasthan',
        'Agile Thinking Jodhpur',
        'Growth Mindset Rajasthan',
        'Learning Mindset Jodhpur',
        'Innovation Mindset Rajasthan',
        'Entrepreneurial Mindset Jodhpur',
        'Leadership Mindset Rajasthan',
        'Collaborative Mindset Jodhpur',
        'Customer-centric Mindset Rajasthan',
        'Quality Mindset Jodhpur',
        'Security Mindset Rajasthan',
        'Performance Mindset Jodhpur',
        'Continuous Improvement Rajasthan',
        'Continuous Learning Jodhpur',
        'Continuous Innovation Rajasthan',
        'Continuous Delivery Jodhpur',
        'Continuous Integration Rajasthan',
        'Continuous Deployment Jodhpur',
        'Continuous Monitoring Rajasthan',
        'Continuous Feedback Jodhpur',
        'Continuous Optimization Rajasthan',
        'Continuous Enhancement Jodhpur',
        'Continuous Evolution Rajasthan',
        'Continuous Adaptation Jodhpur',
        'Continuous Transformation Rajasthan',
        'Continuous Growth Jodhpur',
        'Continuous Success Rajasthan',
        'Sustainable Development Jodhpur',
        'Sustainable Growth Rajasthan',
        'Sustainable Innovation Jodhpur',
        'Sustainable Solutions Rajasthan',
        'Sustainable Practices Jodhpur',
        'Sustainable Technology Rajasthan',
        'Green Technology Jodhpur',
        'Clean Technology Rajasthan',
        'Renewable Energy Solutions Jodhpur',
        'Energy Efficiency Rajasthan',
        'Carbon Footprint Reduction Jodhpur',
        'Environmental Impact Rajasthan',
        'Social Impact Jodhpur',
        'Economic Impact Rajasthan',
        'Community Impact Jodhpur',
        'Regional Impact Rajasthan',
        'National Impact Jodhpur',
        'Global Impact Rajasthan',
        'Industry Impact Jodhpur',
        'Market Impact Rajasthan',
        'Technology Impact Jodhpur',
        'Digital Impact Rajasthan',
        'Innovation Impact Jodhpur',
        'Transformation Impact Rajasthan',
        'Change Impact Jodhpur',
        'Business Impact Rajasthan',
        'Organizational Impact Jodhpur',
        'Team Impact Rajasthan',
        'Individual Impact Jodhpur',
        'Personal Impact Rajasthan',
        'Professional Impact Jodhpur',
        'Career Impact Rajasthan',
        'Skill Impact Jodhpur',
        'Knowledge Impact Rajasthan',
        'Learning Impact Jodhpur',
        'Development Impact Rajasthan',
        'Growth Impact Jodhpur',
        'Success Impact Rajasthan',
        'Achievement Impact Jodhpur',
        'Excellence Impact Rajasthan',
        'Quality Impact Jodhpur',
        'Performance Impact Rajasthan',
        'Efficiency Impact Jodhpur',
        'Productivity Impact Rajasthan',
        'Innovation Impact Jodhpur',
        'Creativity Impact Rajasthan',
        'Problem Solving Impact Jodhpur',
        'Solution Impact Rajasthan',
        'Value Creation Jodhpur',
        'Value Addition Rajasthan',
        'Value Enhancement Jodhpur',
        'Value Optimization Rajasthan',
        'Value Maximization Jodhpur',
        'Return on Investment Rajasthan',
        'Cost Benefit Analysis Jodhpur',
        'Risk Benefit Analysis Rajasthan',
        'Impact Assessment Jodhpur',
        'Feasibility Study Rajasthan',
        'Market Research Jodhpur',
        'Competitive Analysis Rajasthan',
        'SWOT Analysis Jodhpur',
        'Gap Analysis Rajasthan',
        'Needs Assessment Jodhpur',
        'Requirements Gathering Rajasthan',
        'Stakeholder Analysis Jodhpur',
        'User Research Rajasthan',
        'Customer Research Jodhpur',
        'Market Validation Rajasthan',
        'Product Validation Jodhpur',
        'Concept Validation Rajasthan',
        'Idea Validation Jodhpur',
        'Hypothesis Testing Rajasthan',
        'A/B Testing Jodhpur',
        'Multivariate Testing Rajasthan',
        'Split Testing Jodhpur',
        'User Testing Rajasthan',
        'Usability Testing Jodhpur',
        'Accessibility Testing Rajasthan',
        'Performance Testing Jodhpur',
        'Load Testing Rajasthan',
        'Stress Testing Jodhpur',
        'Security Testing Rajasthan',
        'Penetration Testing Jodhpur',
        'Vulnerability Testing Rajasthan',
        'Compliance Testing Jodhpur',
        'Regression Testing Rajasthan',
        'Integration Testing Jodhpur',
        'System Testing Rajasthan',
        'End-to-end Testing Jodhpur',
        'Acceptance Testing Rajasthan',
        'User Acceptance Testing Jodhpur',
        'Business Acceptance Testing Rajasthan',
        'Operational Acceptance Testing Jodhpur',
        'Production Testing Rajasthan',
        'Live Testing Jodhpur',
        'Real-world Testing Rajasthan',
        'Field Testing Jodhpur',
        'Beta Testing Rajasthan',
        'Alpha Testing Jodhpur',
        'Prototype Testing Rajasthan',
        'Proof of Concept Testing Jodhpur',
        'Pilot Testing Rajasthan',
        'Trial Testing Jodhpur',
        'Experimental Testing Rajasthan',
        'Research Testing Jodhpur',
        'Development Testing Rajasthan',
        'Quality Testing Jodhpur',
        'Validation Testing Rajasthan',
        'Verification Testing Jodhpur',
        'Certification Testing Rajasthan',
        'Audit Testing Jodhpur',
        'Review Testing Rajasthan',
        'Inspection Testing Jodhpur',
        'Evaluation Testing Rajasthan',
        'Assessment Testing Jodhpur',
        'Analysis Testing Rajasthan',
        'Measurement Testing Jodhpur',
        'Monitoring Testing Rajasthan',
        'Tracking Testing Jodhpur',
        'Reporting Testing Rajasthan',
        'Documentation Testing Jodhpur',
        'Training Testing Rajasthan',
        'Support Testing Jodhpur',
        'Maintenance Testing Rajasthan',
        'Upgrade Testing Jodhpur',
        'Migration Testing Rajasthan',
        'Deployment Testing Jodhpur',
        'Release Testing Rajasthan',
        'Launch Testing Jodhpur',
        'Go-live Testing Rajasthan',
        'Production Deployment Jodhpur',
        'Live Deployment Rajasthan',
        'Cloud Deployment Jodhpur',
        'Server Deployment Rajasthan',
        'Application Deployment Jodhpur',
        'Database Deployment Rajasthan',
        'Infrastructure Deployment Jodhpur',
        'Platform Deployment Rajasthan',
        'Service Deployment Jodhpur',
        'API Deployment Rajasthan',
        'Microservice Deployment Jodhpur',
        'Container Deployment Rajasthan',
        'Serverless Deployment Jodhpur',
        'Edge Deployment Rajasthan',
        'Multi-cloud Deployment Jodhpur',
        'Hybrid Deployment Rajasthan',
        'On-premise Deployment Jodhpur',
        'Local Deployment Rajasthan',
        'Remote Deployment Jodhpur',
        'Distributed Deployment Rajasthan',
        'Scalable Deployment Jodhpur',
        'High Availability Deployment Rajasthan',
        'Fault Tolerant Deployment Jodhpur',
        'Disaster Recovery Deployment Rajasthan',
        'Backup Deployment Jodhpur',
        'Redundant Deployment Rajasthan',
        'Load Balanced Deployment Jodhpur',
        'Auto Scaling Deployment Rajasthan',
        'Blue Green Deployment Jodhpur',
        'Canary Deployment Rajasthan',
        'Rolling Deployment Jodhpur',
        'Zero Downtime Deployment Rajasthan',
        'Continuous Deployment Jodhpur',
        'Automated Deployment Rajasthan',
        'Manual Deployment Jodhpur',
        'Scheduled Deployment Rajasthan',
        'On-demand Deployment Jodhpur',
        'Emergency Deployment Rajasthan',
        'Hotfix Deployment Jodhpur',
        'Patch Deployment Rajasthan',
        'Update Deployment Jodhpur',
        'Upgrade Deployment Rajasthan',
        'Migration Deployment Jodhpur',
        'Rollback Deployment Rajasthan',
        'Recovery Deployment Jodhpur',
        'Restoration Deployment Rajasthan',
        'Maintenance Deployment Jodhpur',
        'Support Deployment Rajasthan',
        'Monitoring Deployment Jodhpur',
        'Logging Deployment Rajasthan',
        'Analytics Deployment Jodhpur',
        'Reporting Deployment Rajasthan',
        'Dashboard Deployment Jodhpur',
        'Visualization Deployment Rajasthan',
        'Notification Deployment Jodhpur',
        'Alert Deployment Rajasthan',
        'Communication Deployment Jodhpur',
        'Integration Deployment Rajasthan',
        'Synchronization Deployment Jodhpur',
        'Replication Deployment Rajasthan',
        'Backup Deployment Jodhpur',
        'Archive Deployment Rajasthan',
        'Storage Deployment Jodhpur',
        'Database Deployment Rajasthan',
        'Cache Deployment Jodhpur',
        'CDN Deployment Rajasthan',
        'Security Deployment Jodhpur',
        'Authentication Deployment Rajasthan',
        'Authorization Deployment Jodhpur',
        'Encryption Deployment Rajasthan',
        'Firewall Deployment Jodhpur',
        'VPN Deployment Rajasthan',
        'SSL Deployment Jodhpur',
        'Certificate Deployment Rajasthan',
        'Compliance Deployment Jodhpur',
        'Audit Deployment Rajasthan',
        'Governance Deployment Jodhpur',
        'Policy Deployment Rajasthan',
        'Procedure Deployment Jodhpur',
        'Standard Deployment Rajasthan',
        'Framework Deployment Jodhpur',
        'Methodology Deployment Rajasthan',
        'Best Practice Deployment Jodhpur',
        'Tool Deployment Rajasthan',
        'Technology Deployment Jodhpur',
        'Solution Deployment Rajasthan',
        'System Deployment Jodhpur',
        'Process Deployment Rajasthan',
        'Service Deployment Jodhpur',
        'Feature Deployment Rajasthan',
        'Enhancement Deployment Jodhpur',
        'Improvement Deployment Rajasthan',
        'Optimization Deployment Jodhpur',
        'Innovation Deployment Rajasthan',
        'Transformation Deployment Jodhpur',
        'Change Deployment Rajasthan',
        'Evolution Deployment Jodhpur',
        'Growth Deployment Rajasthan',
        'Success Deployment Jodhpur',
        'Excellence Deployment Rajasthan'
    ].join(', '),
    authors: [{ name: 'Harshit Sharma', url: 'https://harshitsharma.dev' }],
    creator: 'Harshit Sharma',
    publisher: 'Harshit Sharma',
    robots: 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1',
    alternates: {
        canonical: 'https://harshitsharma.dev'
    },
    openGraph: {
        title: 'Harshit Sharma - Full Stack Developer in Jodhpur | Next.js Developer Rajasthan',
        description: 'Expert Full Stack Developer in Jodhpur, Rajasthan. Specializing in Next.js, React.js, Node.js, AI/ML solutions. 4.5+ years experience. Best web developer in Jodhpur.',
        type: 'website',
        locale: 'en_IN',
        url: 'https://harshitsharma.dev',
        siteName: 'Harshit Sharma - Full Stack Developer',
        images: [
            {
                url: '/myphoto.JPG',
                width: 1200,
                height: 630,
                alt: 'Harshit Sharma - Full Stack Developer in Jodhpur, Rajasthan'
            }
        ]
    },
    twitter: {
        card: 'summary_large_image',
        title: 'Harshit Sharma - Full Stack Developer in Jodhpur | Next.js Developer Rajasthan',
        description: 'Expert Full Stack Developer in Jodhpur, Rajasthan. Specializing in Next.js, React.js, Node.js, AI/ML solutions. 4.5+ years experience.',
        images: ['/myphoto.JPG'],
        creator: '@harshit_dev',
        site: '@harshit_dev'
    },
    verification: {
        google: 'your-google-verification-code',
        yandex: 'your-yandex-verification-code',
        yahoo: 'your-yahoo-verification-code'
    },
    category: 'Technology',
    classification: 'Business'
}

export const viewport: Viewport = {
    width: 'device-width',
    initialScale: 1,
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const structuredData = {
        "@context": "https://schema.org",
        "@type": "Person",
        "name": "Harshit Sharma",
        "jobTitle": "Senior Full Stack Developer",
        "description": "Expert Full Stack Developer in Jodhpur, Rajasthan specializing in Next.js, React.js, Node.js, and AI/ML solutions",
        "url": "https://harshitsharma.dev",
        "image": "https://harshitsharma.dev/myphoto.JPG",
        "email": "harshit0150@gmail.com",
        "telephone": "+91-99280-05564",
        "address": {
            "@type": "PostalAddress",
            "addressLocality": "Jodhpur",
            "addressRegion": "Rajasthan",
            "addressCountry": "India"
        },
        "worksFor": {
            "@type": "Organization",
            "name": "Now a Wave Technologies Pvt. Ltd."
        },
        "alumniOf": [
            {
                "@type": "EducationalOrganization",
                "name": "Bikaner University"
            },
            {
                "@type": "EducationalOrganization",
                "name": "Jai Narain Vyas University"
            }
        ],
        "knowsAbout": [
            "Full Stack Development",
            "Next.js",
            "React.js",
            "Node.js",
            "JavaScript",
            "TypeScript",
            "MongoDB",
            "Express.js",
            "AI/ML",
            "LangChain",
            "OpenAI API",
            "Web Development",
            "Software Development",
            "Team Leadership",
            "Project Management"
        ],
        "hasOccupation": {
            "@type": "Occupation",
            "name": "Full Stack Developer",
            "occupationLocation": {
                "@type": "City",
                "name": "Jodhpur, Rajasthan, India"
            },
            "skills": "Next.js, React.js, Node.js, JavaScript, TypeScript, MongoDB, AI/ML"
        },
        "sameAs": [
            "https://github.com/harshit-sharma",
            "https://linkedin.com/in/harshit-sharma"
        ]
    }

    return (
        <html lang="en" className="scroll-smooth">
            <head>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
                <link rel="icon" href="/favicon.ico" />
                <script
                    type="application/ld+json"
                    dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
                />
                <meta name="google-site-verification" content="your-google-verification-code" />
                <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" />
                <link rel="canonical" href="https://harshitsharma.dev" />
            </head>
            <body className="bg-black text-white font-inter antialiased">
                {children}
            </body>
        </html>
    )
}